# -*- coding: utf-8 -*-
"""Spread Locater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSEOfnixa5Fpn3ilVLoWqusWk12rtD3N

# Spread Locator: A Statistical Distribution Analysis Model

## Project Overview
You are a data analyst working for an e-commerce platform that wants to understand customer purchase behaviors by analyzing daily transaction amounts of customers. Management is particularly interested in knowing whether the transactions follow certain statistical distributions, how to handle skewed data, and what probability insights can be derived. Your task is to apply statistical distribution concepts and transformations to derive insights on transaction behaviors.

### Dataset Structure Explanation

The synthetic dataset generated for the **Spread Locator** project contains the following fields to model and analyze e-commerce customer transaction behavior:

*   **`transaction_id`** (UUID/String): A unique identifier assigned to every individual transaction.
*   **`customer_id`** (UUID/String): A unique identifier representing the specific customer who made the purchase.
*   **`transaction_amount`** (Float): The total monetary value of the transaction. In the synthetic data, this is modeled using a Log-Normal distribution to simulate realistic e-commerce spending, where most transactions are small-to-medium but a few high-value purchases create a right-skewed distribution.
*   **`transaction_date`** (Date): The specific calendar date on which the transaction occurred.
*   **`transaction_count`** (Int): The total number of transactions completed by the customer within a given week. This metric will be used to fit discrete distributions like the Binomial distribution.
*   **`region`** (String): The geographic region associated with the customer, classified into one of four zones: *North, South, East, or West*.
*   **`transaction_status`** (String): Indicates whether the checkout process was successful or failed (*Success/Fail*). This binary field serves as the foundation for Bernoulli trial analysis.

## Generate the Data set.
"""

import pandas as pd
import numpy as np
import uuid
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(42)

num_records = 1000

# Generate fields based on dataset structure
data = {
    'transaction_id': [str(uuid.uuid4()) for _ in range(num_records)],
    'customer_id': [str(uuid.uuid4()) for _ in range(num_records)],
    # Modeling transaction amounts with a log-normal distribution to simulate e-commerce behavior
    'transaction_amount': np.round(np.random.lognormal(mean=7.5, sigma=0.8, size=num_records), 2),
    'transaction_date': [datetime(2026, 1, 1) + timedelta(days=int(np.random.randint(0, 90))) for _ in range(num_records)],
    'transaction_count': np.random.randint(1, 15, size=num_records),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=num_records),
    'transaction_status': np.random.choice(['Success', 'Fail'], size=num_records, p=[0.85, 0.15])
}

df = pd.DataFrame(data)

# Display the first few rows of the generated dataset
df.head(15)

"""### **Task 1**
**Bernoulli and Binomial Distribution Fitting
Fit the transaction success/failure rates to a Bernoulli distribution to evaluate individual checkout probabilities. Fit the weekly transaction frequencies (transaction_count) to a Binomial distribution to model customer engagement parameters.**
"""

from scipy.stats import bernoulli,binom

#=======================================
# Part:1 Barnoli Distribution
# ======================================

# Count the Total Sucessful Transaction Count.
success_count = (df['transaction_status']== 'Success').sum()

# Total Valid Transacttion count
total_transactions = df['transaction_status'].notna().sum()

# Estimate probability of success
p = success_count / total_transactions

print("Successful transactions:", success_count)
print("Total transactions:", total_transactions)
print("Probability of Success:", p)

# Bernoulli probabilities
print("P(Success):", bernoulli.pmf(1, p))
print("P(Failure):", bernoulli.pmf(0, p))

# ============================================================
# PART 2: BINOMIAL DISTRIBUTION
# ============================================================

# Suppose each customer has 10 possible transaction opportunities
n = 10

# Estimate probability of one successful opportunity
p_binomial = df["transaction_count"].mean() / n

# Possible number of transactions
x = np.arange(0, n + 1)

# Calculate Binomial probability for each possible count
probabilities = binom.pmf(x, n, p_binomial)

print("\nBinomial Results:")

for transactions, probability in zip(x, probabilities):
    print(
        f"{transactions} transactions: "
        f"{probability:.4f}"
    )

"""####**Task 2:**
**Poisson Distribution Modeling
Model the rate of customer transaction volume arriving per day using a Poisson distribution to discover peak activity patterns.**
"""

from scipy.stats import poisson
# ====================================
# Poisson Distribution
# ====================================

# So first we have to make the date column to the date time data type.
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Extract the day only.
df["date"] = df["transaction_date"].dt.date

# Count transaction per day.
daily_transaction = df.groupby('date').size()
daily_transaction


# Calculate the lamda rate.
lambda_rate = daily_transaction.mean()
print("Average transactions per day:", lambda_rate)


# Fit the poision model.
x = range(0, 70)
probabilities = poisson.pmf(x, lambda_rate)


# Make the data frame of poision probabilities
poisson_df = pd.DataFrame({
    "Transactions": x,
    "Probability_percc" : probabilities*100.00
})

print(f"The Poision Probability for Daily Transaction Volume.")
print(poisson_df.head(10))

"""###**Task 3:**
**Transaction Amount Modeling
Analyze and model the transaction_amount field using both Log-Normal and Power Law distributions to assess how well they characterize skewed e-commerce spending behaviors.**
"""

# So for the ploting the log normal and Power law distribution we have to import the matplotlib first.
import matplotlib.pyplot as plt

# Then plot the normal bar graph to see the how our data look like.
plt.figure(figsize=(8,4))
plt.hist(df['transaction_amount'], bins=30)

plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.title("Distribution of Transaction Amounts")

plt.show()

# Use the log normal Function.
log_amount = np.log(df['transaction_amount'])

plt.hist(log_amount, bins=30)

plt.xlabel("Log(Transaction Amount)")
plt.ylabel("Frequency")
plt.title("Log-Transformed Transaction Amount")

plt.show()

from scipy.stats import lognorm
# Fit the log normal distribution.
shape, loc, scale = lognorm.fit(df['transaction_amount'],floc=0)

print("Shape:", shape)
print("Scale:", scale)

# Genearte the log-normal model
x = np.linspace(df['transaction_amount'].min(), df['transaction_amount'].max(), 1000)

lognormal_pdf = lognorm.pdf(
    x,
    shape,
    loc,
    scale
)

plt.hist(
    df['transaction_amount'],
    bins=30,
    density=True,
    alpha=0.6
)

plt.plot(
    x,
    lognormal_pdf
)

plt.xlabel("Transaction Amount")
plt.ylabel("Density")
plt.title("Log-Normal Model vs Transaction Amounts")

plt.show()

"""*   **Task 4: Quantile-Quantile (Q-Q) Plot Analysis**  
    Generate a theoretical Q-Q Plot against a normal distribution to visually check and interpret the degree of normality or skewness in the raw transaction amounts.
"""

# Import our important library that we use to make the plot.
from scipy import stats

# ==========================================
# Prepare the transaction data for ploting
# ===========================================

amount = df['transaction_amount'].dropna()

# Keep only the row that have positive amounts.
amount = amount[amount>0]

# ---------------------------------------
# Create Q-Q plot
# ---------------------------------------

stats.probplot(amount, dist="norm", plot=plt)

plt.title("Q-Q Plot of Transaction Amounts")
plt.xlabel("Theoretical Quantiles")
plt.ylabel("Ordered Transaction Amounts")

plt.show()

"""*   **Task 5:
 Variance Stabilization via Box-Cox Transform**  
    Apply a Box-Cox statistical transformation to the skewed transaction amounts to stabilize variance and transform the target data closer to a normal distribution.

"""

# Import the important library first.
import matplotlib.pyplot as plt
from scipy.stats import boxcox, probplot


# Then we have already the transaxction amount.

# Apply the box-cox Transformation.
transformed_amount, lambda_value = boxcox(amount)
print("Optimal Lambda:", lambda_value)


# Compare original and transformed data

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].hist(amount, bins=30)
axes[0].set_title("Original Transaction Amounts")
axes[0].set_xlabel("Transaction Amount")
axes[0].set_ylabel("Frequency")

axes[1].hist(transformed_amount, bins=30)
axes[1].set_title("Box-Cox Transformed Amounts")
axes[1].set_xlabel("Transformed Amount")
axes[1].set_ylabel("Frequency")

plt.tight_layout()
plt.show()

#  Q-Q plot after transformation

probplot(transformed_amount, dist="norm", plot=plt)

plt.title("Q-Q Plot After Box-Cox Transformation")
plt.xlabel("Theoretical Quantiles")
plt.ylabel("Ordered Transformed Values")

plt.show()

"""*   **Task 6: Z-Score Calculation & Probability Extraction**  
    Compute individual Z-scores for raw transaction amounts to standardize the data. Utilize these Z-scores to calculate the formal probability of a single customer transaction exceeding ₹5,000.


"""

from scipy.stats import norm

# Select valid transaction amounts
amount = df["transaction_amount"].dropna()
amount = amount[amount > 0]

# Mean and standard deviation
mean_amount = amount.mean()
std_amount = amount.std()

# Calculate individual Z-scores
z_scores = (amount - mean_amount) / std_amount

# Add Z-scores to dataframe
df.loc[amount.index, "z_score"] = z_scores

# Z-score for ₹5,000
x = 5000
z_5000 = (x - mean_amount) / std_amount

# Probability of transaction exceeding ₹5,000
probability = 1 - norm.cdf(z_5000)

print("Mean transaction amount:", mean_amount)
print("\nStandard deviation:", std_amount)
print("\nThe Z-Score for the Raw Transaction Amount:""\n",z_scores)
print("\nZ-score for ₹5,000:", z_5000)
print("\nProbability of transaction > ₹5,000:", probability)
print("\nProbability (%):", probability * 100)

"""*   **Task 7: Probability Density (PDF) & Cumulative Distribution (CDF) Functions**  
    Plot the empirical PDF and CDF curves for the transaction amounts, and interpret how cumulative boundaries align with customer purchasing behavior.

"""

import matplotlib.pyplot as plt

# Select valid transaction amounts
amount = df["transaction_amount"].dropna()
amount = amount[amount > 0].sort_values()

# ---------------- PDF ----------------
# Histogram-based empirical density
pdf_values, bin_edges = np.histogram(
    amount,
    bins=30,
    density=True
)

bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

# ---------------- CDF ----------------
# Empirical cumulative probability
cdf_values = np.arange(1, len(amount) + 1) / len(amount)

# ---------------- Plot PDF ----------------
plt.figure(figsize=(8, 5))
plt.plot(bin_centers, pdf_values)
plt.xlabel("Transaction Amount (₹)")
plt.ylabel("Probability Density")
plt.title("Empirical PDF of Transaction Amounts")
plt.grid()
plt.show()

# ---------------- Plot CDF ----------------
plt.figure(figsize=(8, 5))
plt.plot(amount, cdf_values)
plt.xlabel("Transaction Amount (₹)")
plt.ylabel("Cumulative Probability")
plt.title("Empirical CDF of Transaction Amounts")
plt.grid()
plt.show()

# ---------------- Selected CDF boundaries ----------------
boundaries = [1000, 2000, 3000, 5000, 10000]

print("Cumulative probabilities:")

for value in boundaries:
    probability = (amount <= value).mean()
    print(f"Transactions ≤ ₹{value}: {probability:.2%}")

"""*   **Task 8: Final Distribution Selection & Operational Justification**  
    Conclude which statistical distribution provides the best fit for the transaction dataset. Provide an analytical justification for how these insights can optimize business decision-making.

# Task 8: Final Distribution Selection & Operational Justification

### 1. Bernoulli & Binomial
Used for **transaction success/failure and repeated transaction outcomes**. These distributions help measure checkout success and expected customer engagement.

### 2. Poisson
Best suited for **daily transaction volume**. The estimated λ represents average daily activity and helps identify potential peak-demand periods.

### 3. Log-Normal
Best suited for the **overall transaction amount** because spending is positive and right-skewed. It helps understand typical customer spending behavior.

### 4. Power Law
Useful for analyzing the **extreme upper tail** of transaction amounts and identifying unusually large-value transactions.

### 5. Q-Q Plot & Box-Cox
The Q-Q plot evaluates the **normality of raw transaction amounts**, while Box-Cox tests whether transformation can reduce skewness and move the data closer to normality.

### 6. Z-Score
Standardizes transaction amounts and shows how unusual **₹5,000** is relative to the average transaction, including the probability of exceeding this threshold.

### 7. PDF & CDF
PDF shows **where transaction amounts are concentrated**, while CDF establishes **spending boundaries and the percentage of transactions below each boundary**.

## Overall Conclusion

The analysis shows that **no single distribution describes every aspect of the transaction data**. Bernoulli/Binomial model transaction outcomes, Poisson models daily volume, and **Log-Normal is the primary model for transaction amounts**, with Power Law providing additional insight into extreme spending. Together, these results support better **peak-demand planning, customer segmentation, checkout monitoring, and high-value transaction identification**.
"""